name: Test Go
description: tests go-app

runs:
  using: composite
  steps:
    - name: setup go environment
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.19

    - name: install go mods
      shell: bash
      working-directory: ./go-app
      run: go mod download

    - name: run go vet
      shell: bash
      working-directory: ./go-app
      run: go vet ./...

    - name: run go tests
      shell: bash
      working-directory: ./go-app
      run: go test ./... -v
