name: Test Rust
description: tests rust-app

runs:
  using: composite
  steps:
      - name: setup rust environment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run rust tests
        shell: bash
        working-directory: ./rust-app
        run: cargo test
