name: CI

on:
  # Trigger the workflow on push only for the master branch
  push:
    branches:
      - master

  # Trigger the workflow on any pull requests
  pull_request:
    branches:
      - "**"

jobs:
  check-dirty:
    runs-on: ubuntu-20.04

    outputs:
      go: ${{ steps.job-output.outputs.go }}
      ruby: ${{ steps.job-output.outputs.ruby }}
      rust: ${{ steps.job-output.outputs.rust }}

    steps:
      - uses: actions/checkout@v3
        # with:
        #   ssh-key: ${{ secrets.MIREGO_GITHUB_SSH_PRIVATE_KEY }}

      - id: is-dirty
        uses: dorny/paths-filter@v2
        with:
          filters: .github/filters.yml

      - id: job-output
        run: |
          echo "go=${{ steps.is-dirty.outputs.go }}" >> $GITHUB_OUTPUT
          echo "ruby=${{ steps.is-dirty.outputs.ruby }}" >> $GITHUB_OUTPUT
          echo "rust=${{ steps.is-dirty.outputs.rust }}" >> $GITHUB_OUTPUT

  test-go:
    needs: check-dirty
    if: needs.check-dirty.outputs.go == 'true'
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-test-go-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        # with:
        #   ssh-key: ${{ secrets.MIREGO_GITHUB_SSH_PRIVATE_KEY }}

      - uses: ./.github/actions/test-go

  test-ruby:
    needs: check-dirty
    if: needs.check-dirty.outputs.ruby == 'true'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        # with:
        #   ssh-key: ${{ secrets.MIREGO_GITHUB_SSH_PRIVATE_KEY }}

      - uses: ./.github/actions/test-ruby

  test-rust:
    needs: check-dirty
    if: needs.check-dirty.outputs.rust == 'true'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        # with:
        #   ssh-key: ${{ secrets.MIREGO_GITHUB_SSH_PRIVATE_KEY }}

      - uses: ./.github/actions/test-rust